### ISSUE TITLE
Feeds

### ISSUE THREAD

**Issue by thisisparker** [thisisparker/ftd#23]
I'd like to add RSS and JSON Feed for new posted files. That might require some reworking—for one thing, files are not currently dated, and this will likely require that—but I think it's worth doing.

**Comment by strugee** [comment]
You might also publish h-feeds: https://indieweb.org/h-feed

It's super easy; all you have to do is add classes to the HTML.

**Comment by thisisparker** [comment]
Closing this with #27. No JSON Feeds yet but I don't think that's a blocker for release.
