### ISSUE TITLE
"read more" link in header breaks after pagination

### ISSUE THREAD

**Issue by trvrfrd** [thisisparker/ftd#30]
The "read more" link in the site header currently uses a relative path. Post-pagination, this breaks if you're on a page other than the first, e.g. on page 2 it links to https://foiathedead.org/2/about.

I started fixing this myself, then realized I was just fixing the generated HTML, then tried to fix the script that generates the HTML, but my editor was doing something weird with trailing whitespace or newlines or something and I was afraid I was going to break things, so I gave up 🤷‍

**Comment by thisisparker** [comment]
Good catch, and thanks for giving fixing my weird idiosyncratic generator a shot. Should be closed with #33.
