### ISSUE TITLE
Berrien and Picciotto bios

### ISSUE THREAD

**Issue by elizabethyalkut** [thisisparker/ftd#35]
### Jacqueline Berrien
Jacqueline Berrien chaired the Equal Employment Opportunity Commission under President Obama. Her FBI file consists of a background check related to that appointment.

### Concepción Picciotto
Concepción Picciotto was a peace activist who held a continuous vigil across the street from the White House, starting in 1981, until ten days before her death in 2016. Her FBI file includes documentation of several complaints to the FBI, including self-published pamphlets.

NB: how much editorial judgement is appropriate in these summaries? Picciotto's complaints and pamphlets seem pretty conspiracy-theory-ish to me.

**Comment by thisisparker** [comment]
Hi there, thank you again for the contribution! Sorry I wasn't able to address it before the holidays... I've added it into the database and it should appear on the site as soon as Amazon's cache clears for it, a matter of minutes.

Would you like some credit on the about page? Is there a thing I can link to?

(And, re: editorial judgment: I try to play it pretty conservative but I think it's OK to characterize some of that writing as you suggest. This project touches on a lot of people who were paranoid, and I think it makes sense to distinguish the ones that had a firm basis in fact from the ones who did not.)

**Comment by elizabethyalkut** [comment]
Credit would be lovely, thank you; my website is elizabethyalkut.com.

Thanks for the guidance, I will bear that in mind going forward.
