### ISSUE TITLE
Lois Weisberg bio

### ISSUE THREAD

**Issue by elizabethyalkut** [thisisparker/ftd#37]
Lois Weisberg was the first Commissioner of Cultural Affairs for the City of Chicago, from 1989 until January 2011. Her FBI file contains notes from an interview about the finances of the Vietnam Veterans Art Group (which has since become the National Veterans Art Museum), which she championed; her recounting of Jaroslav Kořán's visit to Chicago while Mayor of Prague in 1991; and two documents which remain almost entirely redacted.

**Comment by thisisparker** [comment]
Very sorry for the long delay on this, but I so appreciate it and I've got it in place now!

**Comment by elizabethyalkut** [comment]
No worries, I'm just pleased this project isn't as dead as its subjects.
