### ISSUE TITLE
John Trudell bio

### ISSUE THREAD

**Issue by elizabethyalkut** [thisisparker/ftd#39]
John Trudell (Santee Dakota) was an activist for Native American rights and artist. His FBI file, which as-provided only goes to to 1975 (i.e., it was likely prompted by the February 1973 stand-off between federal agents and Native activists in Wounded Knee, South Dakota, and the subsequent court trials), summarizes his Navy career during the Vietnam War, and his early work with the American Indian Movement. He is characterized as a persuasive, charismatic speaker. Interestingly, the file contains no mention of Trudell's participation in the 1969 occupation of Alcatraz Island, nor the November 1972 occupation of the Bureau of Indian Affairs. The file references a "characterization of AIM and Wounded Knee" attachment which was not included.

**Comment by thisisparker** [comment]
Got it! I split this into two paragraphs so the first part is about the same length as the other capsule bios, but it's all up on the actual page.
